sudo: false

language: generic

env:
  global:
  - 'PATH=$HOME/.cargo/bin/:$PATH'

matrix:
  include:
  - os: linux
    env: TARGET=x86_64-unknown-linux-musl
  #- os: osx
  #  env: TARGET=x86_64-apple-darwin

addons:
  apt:
    packages:
    - upx-ucl

script:
- make bootstrap all
- cp target/$TARGET/release/envsub envsub-$TRAVIS_TAG-$TARGET

before_deploy:
# This is a hack to fix deploy failures from dpl.
# Apparently they thought it wasn't worth pinning octokit.
- rvm 1.9.3 do gem install octokit -v 4.3.0

deploy:
  provider: releases
  api_key:
    secure: imeZd34kwpLJ9lFuUhmydIVqnbf3Ws75doNHMOwBivm+UKuPzEmmgMuWB7j/FUSDI9AaFD1RZjWjvG+bMjlelp6CEArx9vdZPORhjnaSQGbUMsZ1PzFjTOkPeMOa+mweeAeTJkJYZkl8CvnOHwF3wqxiNuTD6m5rzomE6XRsZtBi1LKOz6Ynk/PQ1VoSoXwfa14i12hOYHzZWfET1/7fpm+EcUNjimDF1K44Uhgln7WqiEK32D0rOphkgHYJTaNMEMcm1lT7ModBrw+W83+ydfJfgSTHMz6VT8EXM4ou+9E80oXYAsOS13EOAihp2vxjrsh/h/Acdzzd+QMbJVp7qkI7mDh3M0IMpOMezxqWEFBwXn0SYGwHaRNbHFU0efKjCcqBVKyDRJ09Hu4KBvo/h4Vift0CSQHW4qj0zc5jYu9/nuxWOR8XcbogblJYkBKE+zzzETe8Nv4GdunzPDI30vyerNybcGp4FmMbLYINVYBl4Aslbi8B2MzVuXtqKl6+fGapRZoZWy0kw0aUJWAeU9mP8838L4lwICusd6RiXq2opb8xwpY2fDJkERogxNfyPVjJRDdh9y33RQ8JpCvFKd29cSt7oLb1wmJrNWSBlRXdVCLIRS+1iD4cdEr4LZ/77CPFcOCo2AjFF4p6xf55eFyKCvm3yBWjQmrVJASQXjA=
  file: envsub-$TRAVIS_TAG-$TARGET
  skip_cleanup: true
  on:
    repo: gdvalle/envsub
    tags: true
