[package]
name = "envsub"
version = "0.0.2"
authors = ["Greg Dallavalle <greg.dallavalle@ave81.com>"]

[profile.release]
lto = true
panic = "abort"

[dependencies]
aho-corasick = "*"

[dev-dependencies]
subprocess = "*"
